FROM mcr.microsoft.com/powershell:6.1.0-rc.1-ubuntu-18.04
COPY ./Hello-Centric.ps1 ./tmp
RUN pwsh -c "Install-Module universaldashboard -Acceptlicense -Force"

CMD [ "pwsh","-command","& ./tmp/Hello-Centric.ps1" ]